# Taken from another project, will need updating
version: '3.7'

services:
  db:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db-data:
